# Generated by Django 5.0.3 on 2024-03-23 16:57

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('listing_type', models.BooleanField(default=False, verbose_name='Listing type')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('form', models.BooleanField(default=False, verbose_name='Form')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price')),
                ('status', models.IntegerField(choices=[(0, 'Denied'), (1, 'Accepted'), (2, 'Pending')], default=2)),
                ('payment_method', models.CharField(max_length=255)),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('category', models.CharField(max_length=255, verbose_name='Category')),
                ('condition', models.CharField(max_length=255, verbose_name='Condition')),
                ('clicked', models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Number of interaction')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(editable=False)),
                ('first_name', models.CharField(editable=False)),
                ('last_name', models.CharField(editable=False)),
                ('password', models.UUIDField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email address')),
                ('bio', models.TextField(blank=True, null=True)),
                ('class_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2024), django.core.validators.MaxValueValidator(2028)], verbose_name='Class year')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('time_posted', models.DateTimeField(auto_now_add=True)),
                ('time_sold', models.DateTimeField()),
                ('listing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.listing')),
                ('buyer_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_transactions', to='api.user')),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_transactions', to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='MyBids',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('offered_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('message', models.TextField(blank=True, null=True)),
                ('listing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.listing')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.URLField(verbose_name='Image_URL')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('listing_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.listing')),
                ('profile_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
