# Generated by Django 5.0.3 on 2024-04-09 15:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_listing_clicked_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='clicked',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Number of interaction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='time_sold',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(editable=False),
        ),
    ]
